FROM python:3.11-slim

WORKDIR /app

# Install docker CLI
RUN apt update && apt install -y docker.io

# Copy Requirements.txt
COPY requirements.txt .

# Install dependencies 
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY main.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
